first_app/first_app/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todo/',include('todo.urls')),
]

first_app/todo/urls.py
from unicodedata import name
from django.urls import path 
from .views import todo_details, todo_home, todo_json_home,todo_list,todo_done,todo_delete,todo_edit,todo_update


app_name='todo'

urlpatterns=[
    path('list',todo_list ,name= 'list'),
    path('detail/<str:todo_name>',todo_details ,name= 'detail'),
    path('edit/<str:todo_name>', todo_edit, name='edit'),
    path('update/<str:todo_name>',todo_update, name='update'),
    path('done/<str:todo_name>', todo_done, name='done'),
    path('delete/<str:todo_name>', todo_delete, name='delete'),
    path('home/json',todo_json_home ,name= 'home-json'),
    path('home/<str:todo_name>', todo_home, name='home')

]

first_app/todo/models.py
from django.db import models

# Create your models here.

first_app/todo/views.py
from logging import warning
from multiprocessing import Condition, context
from django.shortcuts import render,HttpResponse,redirect,reverse
from django.http.response import JsonResponse
from pprint import pprint

# Create your views here.
my_todos = {
    'one': {'name':'python', 'priority':'1','is_done':False, 'description':"this is desc"},
    'two': {'name':'django', 'priority':'2','is_done':False,'description':"this is desc"},
    'three': {'name':'node', 'priority':'3','is_done':False,'description':"this is desc"}
}

def todo_json_home(request):
    return JsonResponse(my_todos)

def todo_home(request,**kwargs):
    print(kwargs)
    target_todo_name=kwargs.get('todo_name')
    print("Todo Name: " , target_todo_name)
    todo_details= my_todos.get(target_todo_name)
    return HttpResponse(f"hello from {todo_details} ")
  
def todo_list(request,**kwargs):
   
    return render(request,'todo/todo.html',context={'my_todos':my_todos})

def todo_details(request,**kwargs):
    target_todo_name=kwargs.get('todo_name')
    todo_details= my_todos.get(target_todo_name)
    return render(request,'todo/todo_detail.html',context={'my_todo':todo_details})

def todo_delete(request,**kwargs):
    target_todo_name=kwargs.get('todo_name')
    my_target_todo=my_todos.get(target_todo_name)

    if  my_target_todo.get('is_done'):
         my_todos.pop(target_todo_name)

    else:
        return render(request ,'todo/todo.html',context={'my_todos':my_todos,'warning_msg':"cannot delete unfinished tasks"})

    return redirect(reverse('todo:list'))

def todo_done(request,**kwargs):
    task_name=kwargs.get('todo_name')
    my_target_todo=my_todos.get(task_name)
    my_target_todo['is_done']=True
    return redirect(reverse('todo:list'))

def todo_edit(request,**kwargs):
    target_todo_name=kwargs.get('todo_name')
    # todo_details= my_todos.get(target_todo_name)
    return render(request,'todo/todo_edit.html',context={'my_todo':target_todo_name})

def todo_update(request,**kwargs):
    task_name=kwargs.get('todo_name')
    my_target_todo=my_todos.get(task_name)
    my_target_todo['is_done']=True
    my_target_todo['name']='noname'
    return redirect(reverse('todo:list'))

first_app/todo/templates/todo/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title%} {% endblock%} </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
    <h1>ITI</h1>
    {% block body_content %}
    <h1>default body block</h1>
    {% endblock%}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

first_app/todo/templates/todo/todo.html
{% extends 'todo/base.html' %}
{% load custom_tags %}


 {{ my_var}}
<h1>WELCOME</h1>
{% block body_content %}
{% my_custom_tag as my_var %}
My var: {{my_var}} 

{% if warning_msg %}
<div class="alert alert-danger">{{warning_msg}}</div>
{% endif %}
    <table class="table">

        <thead>
            <th>Name</th>
            <th>Finished</th>
            <th>Description</th>
            <th>Action</th>
        </thead>
        <tbody>
            {% for todo,value in my_todos.items %}

            <tr>
                <td>{{todo}}</td>
                <td>{{value.is_done}}</td>
                <td>{{value.description|my_filter}}</td>
                <td> 
                    <a href="{% url 'todo:detail' todo%}" class="btn btn-info">Detail View</a>
                    <a href="{% url 'todo:done' todo%}" class="btn btn-success">Done</a>
                    <a href="{% url 'todo:edit' todo%}" class="btn btn-warning">Edit</a>
                    <a href="{% url 'todo:delete' todo%}" class="btn btn-danger">Delete</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>

    </table>

{% endblock%}

first_app/todo/templates/todo/todo_detail.html
{% extends 'todo/base.html' %}
{% block body_content  %}
  <div class="card mx-5 bg-info" style="width: 18rem;">
    <h1>{{my_todo.name}}</h1>
  <h1>{{my_todo.priority}}</h1>
  <a href="{% url 'todo:list'%}">Back Home</a>
{% endblock %}
</div>

first_app/todo/templates/todo/todo_edit.html
{% extends 'todo/base.html' %}
{% block body_content  %}

<div class="card mx-5 bg-info" style="width: 25rem;">

<a href="{% url 'todo:update'  my_todo %}" class="btn btn-success">update</a>
</div>
{% endblock %}